name: Build Docker Images

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trailofbits/polytracker
    - name: Build the demo Docker image
      run: docker build . --file Dockerfile.demo --tag trailofbits/polytracker-demo
