name: Build Docker Images

on: push

jobs:
  cpp_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: try install clang-format-10
        run: |
          sudo apt install -y software-properties-common gnupg wget
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
          sudo apt-get update -y 
          sudo apt-get install -y clang-format-10
      - name: update submodules 
        run: git submodule update --init --recursive
      - name: lint 
        run: |
          python3 third_party/run-clang-format/run-clang-format.py \
          polytracker/include/dfsan/*.h  polytracker/src/*/*.cpp \
          --exclude 'polytracker/src/dfsan_rt/sanitizer_common/*' \
          --exclude 'polytracker/src/dfsan_rt/interception/*'
      - name: Build the base image 
        run: docker build . --file Dockerfile --tag trailofbits/polytracker --no-cache
