name: Build Docker Images

on: [push]

jobs:
  build_base:
    runs-on: ubuntu-latest 
    steps:
      - name: Prunen images 
        run: docker system prune
      - name: Build the base image 
        run: docker build . --file Dockerfile --tag trailofbits/polytracker --no-cache
      - name: Build the pdfium demo Docker image
        run: docker build . --file examples/Dockerfile-pdfium.demo --tag trailofbits/polytracker-demo-pdfium --no-cache
      - name: Build the mupdf demo Docker image
        run: docker build . --file examples/Dockerfile-mupdf.demo --tag trailofbits/polytracker-demo-mupdf
      - name: Build the poppler demo Docker image
        run: docker build . --file examples/Dockerfile-poppler.demo --tag trailofbits/polytracker-demo-poppler
      - name: Build the qpdf demo Docker image
        run: docker build . --file examples/Dockerfile-qpdf.demo --tag trailofbits/polytracker-demo-qpdf
  
  tests:
    needs: build_base
    runs-on: ubuntu-latest

    steps: 
      - name: Running tests 
        run: docker run --rm -v $(pwd)/polytracker/tests:/test trailofbits/polytracker /test/py.test
